language: php

branches:
  only:
    - master
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

notifications:
  email:
    - typo3@helhum.io

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

addons:
  apt:
    packages:
      - parallel

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer require --dev typo3/minimal=$TYPO3_VERSION

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    mkdir -p .Build/var/lock
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'

jobs:
  fast_finish: true
  include:
    - stage: test
      php: 7.4
      env: TYPO3_VERSION=^10.4
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^10.4
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^10.4
    - stage: test
      php: 7.4
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5

    - stage: 🚢 to TER
      if: tag IS present
      php: 7.2
      install: skip
      before_script: skip
      script:
        - |
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
            # Install ter client
            composer global require helhum/ter-client

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/ter-client upload typoscript_rendering . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
          fi;
